---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
  # 删除 argo 应用的时候同时删除部署的集群资源
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # 指定要更新的镜像列表
    argocd-image-updater.argoproj.io/image-list: qsfda/nginx
    # 设置 qsfda/nginx 镜像的更新策略为 'latest'，即总是使用最新的标签
    # argocd-image-updater.argoproj.io/「image name」.update-strategy
    argocd-image-updater.argoproj.io/qsfda-nginx.update-strategy: latest
    # 指定更新后如何写回变更。这里使用 Git 方式，凭证存储在 argocd 命名空间的 git-creds secret 中
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    # 指定要更新的 Git 分支为 master
    argocd-image-updater.argoproj.io/git-branch: master
    # 使用正则表达式匹配以 dev- 结尾的标签
    argocd-image-updater.argoproj.io/my-registry/my-app.tag-match: ^dev-[0-9]+\.[0-9]+\.[0-9]$
    # 在同步过程中，如果有需要删除的资源，它们将被最后删除。
    argocd.argoproj.io/sync-options: PruneLast=true
    # ArgoCD 检查 Git 仓库是否有变更的过程的间隔，单位秒
    argocd.argoproj.io/refresh: "60"
spec:
  project: default
  source:
    repoURL: https://github.com/gaosong-JGmIQ/argocd-demo.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
