---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
  # 删除 argo 应用的时候同时删除部署的集群资源
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # 在同步过程中，如果有需要删除的资源，它们将被最后删除。
    argocd.argoproj.io/sync-options: PruneLast=true
    # ArgoCD 检查 Git 仓库是否有变更的过程的间隔，单位秒
    argocd.argoproj.io/refresh: "60"
spec:
  project: default
  source:
    repoURL: https://github.com/gaosong-JGmIQ/argocd-demo.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
